language: rust
rust:
  - 1.47.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: 1.47.0
    - rust: beta
    - rust: nightly
script: cargo build --all-targets --workspace --verbose && cargo test --verbose --workspace
